apiVersion: v1
kind: Service
metadata:
  name: asserting-wl
spec:
  type: LoadBalancer
  ports:
   - name: http
     port: 8443
     protocol: TCP
     targetPort: awl-port
  selector:
      app: asserting-wl