apiVersion: v1
kind: Service
metadata:
  name: middle-tier
spec:
  type: LoadBalancer
  ports:
   - name: http
     port: 8445
     protocol: TCP
     targetPort: middle-port
  selector:
      app: middle-tier